### ISSUE TITLE
Open Source link returns 404

### ISSUE THREAD

**Issue by skibum55** [pivotal-cf/docs-blackduck#7]
The open source [link](https://github.com/blackducksoftware/hub-pivotal-cf) on this [line]( https://github.com/pivotal-cf/docs-blackduck/blob/498011679deb4bb6e0a2d5eab1ff51a4a5e72a77/docs-content/index.html.md.erb#L72) returns a 404 not found error.

**Comment by jknostman3** [comment]
@skibum55 Thanks for bringing this to our attention. I have updated the broken link to one that works. Please see the updated [page](http://docs.pivotal.io/partners/blackduck-service-broker/).
